package com.html ;

public class WriteHtml{
	public static StringBuffer getJsDetailHTML(String zc , String day , String classroom){
		StringBuffer buf = new StringBuffer() ;
		buf.append("<!DOCTYPE html>") ;
		buf.append("<html>") ;
		buf.append("<head>") ;
		buf.append("<meta charset=\"utf-8\" />") ;
		buf.append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0,minimum-scale=1.0,user-scalable=0\" />") ;
		buf.append("<title></title>") ;
		buf.append("<style type=\"text/css\">") ;
		buf.append("*{margin:0px;padding:0px;overflow:hidden;font-size:12px;border:0px;}") ;
		buf.append("#container{background:url(blackbord.jpg);width:100%;overflow:auto ;}") ;
		buf.append("#container .box{width:100%;height:300px;}") ;
		buf.append(".box .panel{background:url(empty1.png);width:90%;height:90%;margin:15px auto;border:3px solid #be8080;}") ;
		buf.append("</style>") ;
		buf.append("</head>") ;
		buf.append("<body>") ;
		buf.append("<div id=\"container\">") ;
		buf.append("<div class=\"box c1\">") ;
		buf.append("<div class=\"panel\"></div>") ;
		buf.append("</div>") ;
		buf.append("<div class=\"box c2\">") ;
		buf.append("<div class=\"panel\"></div>") ;
		buf.append("</div>") ;
		buf.append("<div class=\"box c3\">") ;
		buf.append("<div class=\"panel\"></div>") ;
		buf.append("</div>") ;
		buf.append("<div class=\"box c4\">") ;
		buf.append("<div class=\"panel\"></div>") ;
		buf.append("</div>") ;
		buf.append("<div class=\"box c5\">") ;
		buf.append("<div class=\"panel\"></div>") ;
		buf.append("</div>") ;
		buf.append("</div>") ;
		buf.append("</body>") ;
		buf.append("<script type=\"text/javascript\" src=\"jquery.js\"></script>") ;
		buf.append("<script type=\"text/javascript\">") ;
		buf.append("var height = parent.init.clientHeight ;") ;
		buf.append("var width = parent.init.clientWidth ;") ;
		buf.append("var zc = "+zc+" ;") ;
		buf.append("var day = "+day+" ;") ;
		buf.append("var classroom = \""+classroom+"\" ;") ;
		buf.append("$(function(){") ;
		buf.append("$(\"#container\").css(\"height\" , height + \"px\") ;") ;
		buf.append("$.ajax({ ") ;
		buf.append("type:\"GET\" , ") ;
		buf.append("url:\"user.do?method=clasdetail&zc=\"+zc+\"&day=\"+day+\"&classroom=\"+classroom , ") ;
		buf.append("dataType:\"json\" , ") ;
		buf.append("success:function(data){ ") ;
		buf.append("if(typeof(data.code)==\"undefined\"){ ") ;
		buf.append("resultShow(data) ; ") ;
		buf.append("}else{ ") ;
		buf.append("} ; ") ;
		buf.append("parent.loadShow(\"none\") ; ") ;
		buf.append("} , error:function(){ ") ;
		buf.append("parent.loadShow(\"none\") ; ") ;
		buf.append("} ") ;
		buf.append("}) ; ") ;
		buf.append("}) ; ") ;
		buf.append("//处理返回数据\n") ;
		buf.append("function resultShow(data) { ") ;
		buf.append("for(var i=1 ; i<=5 ; i++){ ") ;
		buf.append("if(typeof(data[i].classname) != \"undefined\"){") ;
		buf.append("var line = $(\"<div style='width:98%;margin:0px auto;'></div>\") ;") ;
		buf.append("var classroom = $(\"<div style='width:100%;height:54px;font-size:18px;line-height:54px;color:white;'>教室：\"+data[i].classroom+\"</div>\") ; ") ;
		buf.append("var classes = $(\"<div style='width:100%;height:54px;font-size:18px;line-height:54px;color:white;'>班级：\"+data[i].classes+\"</div>\") ; ") ;
		buf.append("var teacher = $(\"<div style='width:100%;height:54px;font-size:18px;line-height:54px;color:white;'>老师：\"+data[i].teacher+\"</div>\") ; ") ;
		buf.append("var time = $(\"<div style='width:100%;height:54px;font-size:18px;line-height:54px;color:white;'>时间：第\"+zc+\"周 星期\"+day+\" 第\"+i+\"节课</div>\") ; ") ;
		buf.append("var classname = $(\"<div style='width:100%;height:54px;font-size:18px;line-height:54px;color:white;'>课程：\"+data[i].classname+\"</div>\") ; ") ;
		buf.append("line.append(classroom).append(classes).append(teacher).append(time).append(classname) ; ") ;
		buf.append("$(\".c\"+i+\" .panel\").append(line) ; ") ;
		buf.append("}else{ ") ;
		buf.append("var line = $(\"<div style='width:98%;margin:0px auto;'></div>\") ; ") ;
		buf.append("var detail = $(\"<div style='width:100%;height:100%;font-size:18px;line-height:270px;color:white;text-align:center;'>没有课</div>\") ; ") ;
		buf.append("line.append(detail) ; " ) ;
		buf.append("$(\".c\"+i+\" .panel\").append(line) ; " ) ;
		buf.append("} " ) ;
		buf.append("} " ) ;
		buf.append("} " ) ;
		buf.append("</script>") ;
		buf.append("</html>" ) ;

		return buf ;
	}
}